version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEV_ENV=${DEV_ENV}
      - TEST_ENV=${TEST_ENV}
      - COMPOSER=True
#    command:
#      - uvicorn --port 8000 --app-dir /code api.entry:app