name: Upload to S3
on:
  pull_request:
    types: [ closed ]

permissions:
  contents: read
jobs:
  upload_s3:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo PR ${{ github.event.number }} has been merged
    - name: Upload S3
      id: S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{secrets.AWS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ping-pong-api-repo
        source_dir: .